/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R3dRouteImport } from './routes/3d'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MapRouteImport } from './routes/map'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as RoomRouteImport } from './routes/room'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdventuresRouteImport } from './routes/admin.adventures'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminHeumarktRouteImport } from './routes/admin.heumarkt'
import { Route as AdminItemsRouteImport } from './routes/admin.items'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminPuzzlesRouteImport } from './routes/admin.puzzles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStagesRouteImport } from './routes/admin.stages'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as PuzzleIdRouteImport } from './routes/puzzle.$id'
import { Route as StageIdRouteImport } from './routes/stage.$id'
import { Route as AdminAdventureIdRouteImport } from './routes/admin.adventure.$id'
import { Route as AdminStageIdRouteImport } from './routes/admin.stage.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dRoute = R3dRouteImport.update({
  id: '/3d',
  path: '/3d',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdventuresRoute = AdminAdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeumarktRoute = AdminHeumarktRouteImport.update({
  id: '/heumarkt',
  path: '/heumarkt',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPuzzlesRoute = AdminPuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStagesRoute = AdminStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => AdminRoute,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleIdRoute = PuzzleIdRouteImport.update({
  id: '/puzzle/$id',
  path: '/puzzle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StageIdRoute = StageIdRouteImport.update({
  id: '/stage/$id',
  path: '/stage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdventureIdRoute = AdminAdventureIdRouteImport.update({
  id: '/adventure/$id',
  path: '/adventure/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStageIdRoute = AdminStageIdRouteImport.update({
  id: '/stage/$id',
  path: '/stage/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d': typeof R3dRoute
  '/admin': typeof AdminRouteWithChildren
  '/adventure': typeof AdventureRoute
  '/complete': typeof CompleteRoute
  '/inventory': typeof InventoryRoute
  '/journal': typeof JournalRoute
  '/map': typeof MapRoute
  '/puzzles': typeof PuzzlesRoute
  '/room': typeof RoomRoute
  '/scan': typeof ScanRoute
  '/admin/adventures': typeof AdminAdventuresRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/heumarkt': typeof AdminHeumarktRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/puzzles': typeof AdminPuzzlesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stages': typeof AdminStagesRoute
  '/item/$id': typeof ItemIdRoute
  '/puzzle/$id': typeof PuzzleIdRoute
  '/stage/$id': typeof StageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/adventure/$id': typeof AdminAdventureIdRoute
  '/admin/stage/$id': typeof AdminStageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d': typeof R3dRoute
  '/adventure': typeof AdventureRoute
  '/complete': typeof CompleteRoute
  '/inventory': typeof InventoryRoute
  '/journal': typeof JournalRoute
  '/map': typeof MapRoute
  '/puzzles': typeof PuzzlesRoute
  '/room': typeof RoomRoute
  '/scan': typeof ScanRoute
  '/admin/adventures': typeof AdminAdventuresRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/heumarkt': typeof AdminHeumarktRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/puzzles': typeof AdminPuzzlesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stages': typeof AdminStagesRoute
  '/item/$id': typeof ItemIdRoute
  '/puzzle/$id': typeof PuzzleIdRoute
  '/stage/$id': typeof StageIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/adventure/$id': typeof AdminAdventureIdRoute
  '/admin/stage/$id': typeof AdminStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d': typeof R3dRoute
  '/admin': typeof AdminRouteWithChildren
  '/adventure': typeof AdventureRoute
  '/complete': typeof CompleteRoute
  '/inventory': typeof InventoryRoute
  '/journal': typeof JournalRoute
  '/map': typeof MapRoute
  '/puzzles': typeof PuzzlesRoute
  '/room': typeof RoomRoute
  '/scan': typeof ScanRoute
  '/admin/adventures': typeof AdminAdventuresRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/heumarkt': typeof AdminHeumarktRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/puzzles': typeof AdminPuzzlesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stages': typeof AdminStagesRoute
  '/item/$id': typeof ItemIdRoute
  '/puzzle/$id': typeof PuzzleIdRoute
  '/stage/$id': typeof StageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/adventure/$id': typeof AdminAdventureIdRoute
  '/admin/stage/$id': typeof AdminStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3d'
    | '/admin'
    | '/adventure'
    | '/complete'
    | '/inventory'
    | '/journal'
    | '/map'
    | '/puzzles'
    | '/room'
    | '/scan'
    | '/admin/adventures'
    | '/admin/events'
    | '/admin/heumarkt'
    | '/admin/items'
    | '/admin/locations'
    | '/admin/players'
    | '/admin/puzzles'
    | '/admin/settings'
    | '/admin/stages'
    | '/item/$id'
    | '/puzzle/$id'
    | '/stage/$id'
    | '/admin/'
    | '/admin/adventure/$id'
    | '/admin/stage/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3d'
    | '/adventure'
    | '/complete'
    | '/inventory'
    | '/journal'
    | '/map'
    | '/puzzles'
    | '/room'
    | '/scan'
    | '/admin/adventures'
    | '/admin/events'
    | '/admin/heumarkt'
    | '/admin/items'
    | '/admin/locations'
    | '/admin/players'
    | '/admin/puzzles'
    | '/admin/settings'
    | '/admin/stages'
    | '/item/$id'
    | '/puzzle/$id'
    | '/stage/$id'
    | '/admin'
    | '/admin/adventure/$id'
    | '/admin/stage/$id'
  id:
    | '__root__'
    | '/'
    | '/3d'
    | '/admin'
    | '/adventure'
    | '/complete'
    | '/inventory'
    | '/journal'
    | '/map'
    | '/puzzles'
    | '/room'
    | '/scan'
    | '/admin/adventures'
    | '/admin/events'
    | '/admin/heumarkt'
    | '/admin/items'
    | '/admin/locations'
    | '/admin/players'
    | '/admin/puzzles'
    | '/admin/settings'
    | '/admin/stages'
    | '/item/$id'
    | '/puzzle/$id'
    | '/stage/$id'
    | '/admin/'
    | '/admin/adventure/$id'
    | '/admin/stage/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dRoute: typeof R3dRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdventureRoute: typeof AdventureRoute
  CompleteRoute: typeof CompleteRoute
  InventoryRoute: typeof InventoryRoute
  JournalRoute: typeof JournalRoute
  MapRoute: typeof MapRoute
  PuzzlesRoute: typeof PuzzlesRoute
  RoomRoute: typeof RoomRoute
  ScanRoute: typeof ScanRoute
  ItemIdRoute: typeof ItemIdRoute
  PuzzleIdRoute: typeof PuzzleIdRoute
  StageIdRoute: typeof StageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d': {
      id: '/3d'
      path: '/3d'
      fullPath: '/3d'
      preLoaderRoute: typeof R3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/adventures': {
      id: '/admin/adventures'
      path: '/adventures'
      fullPath: '/admin/adventures'
      preLoaderRoute: typeof AdminAdventuresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/heumarkt': {
      id: '/admin/heumarkt'
      path: '/heumarkt'
      fullPath: '/admin/heumarkt'
      preLoaderRoute: typeof AdminHeumarktRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/puzzles': {
      id: '/admin/puzzles'
      path: '/puzzles'
      fullPath: '/admin/puzzles'
      preLoaderRoute: typeof AdminPuzzlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stages': {
      id: '/admin/stages'
      path: '/stages'
      fullPath: '/admin/stages'
      preLoaderRoute: typeof AdminStagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$id': {
      id: '/puzzle/$id'
      path: '/puzzle/$id'
      fullPath: '/puzzle/$id'
      preLoaderRoute: typeof PuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/$id': {
      id: '/stage/$id'
      path: '/stage/$id'
      fullPath: '/stage/$id'
      preLoaderRoute: typeof StageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adventure/$id': {
      id: '/admin/adventure/$id'
      path: '/adventure/$id'
      fullPath: '/admin/adventure/$id'
      preLoaderRoute: typeof AdminAdventureIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stage/$id': {
      id: '/admin/stage/$id'
      path: '/stage/$id'
      fullPath: '/admin/stage/$id'
      preLoaderRoute: typeof AdminStageIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdventuresRoute: typeof AdminAdventuresRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHeumarktRoute: typeof AdminHeumarktRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminPuzzlesRoute: typeof AdminPuzzlesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStagesRoute: typeof AdminStagesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdventureIdRoute: typeof AdminAdventureIdRoute
  AdminStageIdRoute: typeof AdminStageIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdventuresRoute: AdminAdventuresRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminHeumarktRoute: AdminHeumarktRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminPuzzlesRoute: AdminPuzzlesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStagesRoute: AdminStagesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdventureIdRoute: AdminAdventureIdRoute,
  AdminStageIdRoute: AdminStageIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dRoute: R3dRoute,
  AdminRoute: AdminRouteWithChildren,
  AdventureRoute: AdventureRoute,
  CompleteRoute: CompleteRoute,
  InventoryRoute: InventoryRoute,
  JournalRoute: JournalRoute,
  MapRoute: MapRoute,
  PuzzlesRoute: PuzzlesRoute,
  RoomRoute: RoomRoute,
  ScanRoute: ScanRoute,
  ItemIdRoute: ItemIdRoute,
  PuzzleIdRoute: PuzzleIdRoute,
  StageIdRoute: StageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
