/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as MapRouteImport } from './routes/map'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as PuzzleIdRouteImport } from './routes/puzzle.$id'
import { Route as StageIdRouteImport } from './routes/stage.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleIdRoute = PuzzleIdRouteImport.update({
  id: '/puzzle/$id',
  path: '/puzzle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StageIdRoute = StageIdRouteImport.update({
  id: '/stage/$id',
  path: '/stage/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/map': typeof MapRoute
  '/puzzles': typeof PuzzlesRoute
  '/puzzle/$id': typeof PuzzleIdRoute
  '/stage/$id': typeof StageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/map': typeof MapRoute
  '/puzzles': typeof PuzzlesRoute
  '/puzzle/$id': typeof PuzzleIdRoute
  '/stage/$id': typeof StageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/map': typeof MapRoute
  '/puzzles': typeof PuzzlesRoute
  '/puzzle/$id': typeof PuzzleIdRoute
  '/stage/$id': typeof StageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/adventure' | '/map' | '/puzzles' | '/puzzle/$id' | '/stage/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adventure' | '/map' | '/puzzles' | '/puzzle/$id' | '/stage/$id'
  id:
    | '__root__'
    | '/'
    | '/adventure'
    | '/map'
    | '/puzzles'
    | '/puzzle/$id'
    | '/stage/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventureRoute: typeof AdventureRoute
  MapRoute: typeof MapRoute
  PuzzlesRoute: typeof PuzzlesRoute
  PuzzleIdRoute: typeof PuzzleIdRoute
  StageIdRoute: typeof StageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$id': {
      id: '/puzzle/$id'
      path: '/puzzle/$id'
      fullPath: '/puzzle/$id'
      preLoaderRoute: typeof PuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/$id': {
      id: '/stage/$id'
      path: '/stage/$id'
      fullPath: '/stage/$id'
      preLoaderRoute: typeof StageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventureRoute: AdventureRoute,
  MapRoute: MapRoute,
  PuzzlesRoute: PuzzlesRoute,
  PuzzleIdRoute: PuzzleIdRoute,
  StageIdRoute: StageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
